spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    show-sql: false
    properties:
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true

  datasource:
    url: jdbc:h2:mem:tuition_db;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
    username: sa
    password:
    driver-class-name: org.h2.Driver
  sql:
    init:
      data-locations: classpath:data/data.sql

app:
  instrumentation-config:
    stats-d-client-prefix: statsd
    agent-host: localhost
    agent-port: 8125

server:
  port: 8082